# Generated by Django 5.0.6 on 2024-09-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantinfo',
            options={'verbose_name': 'Tenant Information', 'verbose_name_plural': 'Tenant Information'},
        ),
    ]
