# Generated by Django 5.0.6 on 2024-09-15 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TauxDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('taux_actuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taux de Déduction',
                'verbose_name_plural': 'Taux de Déduction',
                'ordering': ['nom', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TauxDeductionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newTaux', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField()),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='taux.tauxdeduction')),
            ],
            options={
                'verbose_name': 'Historique du Taux de Déduction',
                'verbose_name_plural': 'Historiques des Taux de Déduction',
                'ordering': ['taux', 'date_debut'],
            },
        ),
    ]
