# Generated by Django 5.0.6 on 2024-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiedetail',
            name='valeur_deduction',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
